---
- name: Load vars for distribution
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_os_family|lower }}/{{ ansible_distribution|lower }}/{{ ansible_distribution_major_version }}.yml"
    - "{{ ansible_os_family|lower }}/{{ ansible_distribution|lower }}.yml"
    - "{{ ansible_os_family|lower }}.yml"
    - main.yml

- name: Include any OS specific Docker configuration
  include: "{{ ansible_os_family|lower() }}-{{ ansible_pkg_mgr }}.yml"

- name: Create RabbitMQ configuration
  template:
    src: etc/rabbitmq/rabbitmq.config
    dest: /etc/rabbitmq/rabbitmq.config
    owner: "{{ rabbitmq_system_user }}"
    group: "{{ rabbitmq_system_user_group }}"
  become: true

- name: Add users to RabbitMQ
  rabbitmq_user:
    user: "{{ item.name }}"
    password: "{{ item.password }}"
    vhost: "{{ item.vhost|default('/') }}"
    configure_priv: "{{ item.config_priv|default('.*') }}"
    read_priv: "{{ item.read_priv|default('.*') }}"
    write_priv: "{{ item.write_priv|default('.*') }}"
    state: present
  with_items: "{{ rabbitmq_users }}"
  become: true

- name: Add vhosts
  rabbitmq_vhost:
    name: "{{ item.name }}"
    tracing: "{{ item.tracing|default('no') }}"
    state: present
  become: true
  with_items: "{{ rabbitmq_vhosts }}"

- name: Add plugins
  rabbitmq_plugin:
    name: "{{ item }}"
    state: present
  become: true
  with_items: "{{ rabbitmq_plugins }}"
